name: kiyak
description: A new Flutter project

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2


flutter:
  assets:
    - assets/my_design.yaml





environment:
  sdk: '>=2.12.0 <3.0.0'





